name: Variables
description: "Set variables for use in other actions"

runs:
  using: composite
  steps:
    - name: Set variables
      shell: bash
      run: |
        echo "Setting variables..."
        echo "FBA_IMAGE_NAME=${{ github.repository }}" >> "$GITHUB_ENV"
        echo "FBA_IMAGE_TAG=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
