name: Variables
description: "Set variables for use in other actions"

runs:
  using: composite
  steps:
    - name: Set variables
      shell: bash
      env:
        IMAGE_NAME: ""
        IMAGE_TAG: ""
      run: |
        echo ::set-env name=IMAGE_NAME::${{ github.repository }}; \
        echo ::set-env name=IMAGE_TAG::$(git describe --tags --abbrev=0) ; \
        echo ${{ toJSON(env) }} >> $GITHUB_ENV ; \
        echo ${{ toJSON(steps) }} ; \
