name: Variables
description: "Set variables for use in other actions"

runs:
  using: composite
  steps:
    - name: Set variables
      shell: bash
      env:
        IMAGE_NAME: ${{ github.repository}}
        IMAGE_TAG: $(git describe --tags --abbrev=0)
      run: |
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
