name: Variables
description: "Set variables for use in other actions"

runs:
  using: composite
  steps:
    - name: Set variables
      shell: bash
      run: |
        FBA_IMAGE_NAME=${{ github.repository }} >> variables.env; \
        FBA_IMAGE_TAG=$(git describe --tags --abbrev=0) >> variables.env; \

    - name: Set outputs
      id: vars
      shell: bash
      run: |
        echo $(cat variables.env)
