name: Develop

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
    check:
      name: Ckeck 
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        - name: Validate
          uses: dolorestec/devops/.github/workflows/validate.yml@v1