name: Develop

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
    validate:
      name: Validate
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        - name: Create Release Branch
          uses: dolorestec/devops/.github/workflows/create-release-branch.yml@v1 