name: Develop

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
    check:
      name: Check 
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

    

      - name: Create Variables file
        #uses: dolorestec/devops/.github/workflows/validate.yml@v1
        run: |
          echo "Criando arquivo de variaveis" >> "$GITHUB_OUTPUT"


