name: Docker - Build and Upload

on:
    workflow_call:
    
    workflow_dispatch:

jobs:                
    build-upload:
        name: Build and Upload
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                repository: ${{ github.repository }}
                ref: ${{ github.ref_name }}
                fetch-depth: 0

            - name: Build docker image
              id: build
              uses: ./.github/actions/docker/build

            - name: Upload docker image
              uses: ./.github/actions/docker/upload
              with:
                docker_username: ${{ secrets.DOCKER_USERNAME }}
                docker_password: ${{ secrets.DOCKER_PASSWORD }}
