name: Merge on Develop

on:
  push:
    branches:
      - develop
    tags:
      - v*-RELEASE*

  workflow_dispatch:

jobs:
    variables:
      uses: dolorestec/devops/.github/workflows/release-branch.yml@v1 
    
