name: Merge on Develop

on:
  push:
    branches:
      - develop
    tags:
      - v*-RELEASE*

  workflow_dispatch:

jobs:
    variables:
      name: Variables
      uses: dolorestec/devops/.github/workflows/release-branch.yml@v1 
    
    build:
        name: Build
        timeout-minutes: 10
        runs-on: ubuntu-latest
        needs: variables
        steps:
            - name: pass3
              run: |
                echo "passo 3"

            - name: pass4
              run: |
                echo "passo 4"