name: Merge on Develop

on:
  push:
    branches:
      - develop
    tags:
      - v*-RELEASE*

  workflow_dispatch:

jobs:
    variables:
      uses: dolorestec/devops/.github/workflows/release-branch.yml@v1 
      
    docker:
      name: Docker
      runs-on: ubuntu-latest
      needs: variables
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Download variables
          uses: actions/download-artifact@v2
          with:
            name: variables.txt

        - name: Setting variables
          run: |
            echo "Setting variables from variables file"
            variables=$(cat variables.txt)
            cat variables.txt
            for variable in $variables; do
              echo -e $variable >> $GITHUB_ENV
              echo -e $variable
            done

        - name: Docker build
          run: |
            echo "Building docker image $DLRS_NAME:$DLRS_VERSION"
            docker build -t $DLRS_NAME:$DLRS_VERSION .  

        - name: Docker login
          run: |
            echo "Logging into docker"
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
        - name: Docker push
          run: |
            echo "Pushing docker image"
            docker push $DLRS_NAME:$DLRS_VERSION

        - name: Docker logout
          run: |
            echo "Logging out of docker"
            docker logout

    release_branch:
      
        name: Release Branch
        runs-on: ubuntu-latest
        needs: docker
        steps:
          - name: Checkout
            run:
              echo "Checking out"
              git checkout $DLRS_BRANCH
    
