name: Release Branch

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
    release-branch:
      #uses: dolorestec/devops/.github/workflows/release-branch.yml@v1 
      name: Variables
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Creating variables
          run: |
            touch variables.json
            chmod 777 variables.json

        - name: LS arquivo
          run: |
            ls -la

        - name: Setting variables
          env:
            DLRS_NAME: ${{ github.repository }}
            DLRS_BRANCH: ${{ github.ref_name }}
            DLRS_VERSION: $(git tag --sort creatordate -l "v*-RELEASE*" --merged)       
          run: |
            echo ${{env.DLRS_NAME}}
            echo ${{env.DLRS_BRANCH}}
            echo ${{env.DLRS_VERSION}}


        - name: Upload variables
          run: |
            cat variables.json

    finish:
        name: Finish
        needs: release-branch
        runs-on: ubuntu-latest

        steps:
          - name: Print variables
            run: |
              echo $DLRS_NAME
              echo $DLRS_BRANCH
              echo $DLRS_VERSION