name: Release Candidate

on:
  workflow_dispatch:

jobs:
    envoirenment:
        name: Envoirenment
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                repository: ${{ github.repository }}
                ref: ${{ github.ref_name }}
                fetch-depth: 0
            
            - name: Setting variables
              uses: ./.github/actions/utils/variables

            - name: Upload variables as artifacts
              run: |
                echo ${{env.FBA_IMAGE_NAME}}
            

