name: Release Branch

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
    release-branch:
      #uses: dolorestec/devops/.github/workflows/release-branch.yml@v1 
      name: Variables
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Setting variables
          run: |
            echo -e $(export DLRS_NAME=$(echo ${{ github.repository }})) >> $GITHUB_ENV
            echo -e $(export DLRS_BRANCH=$(echo ${{ github.ref_name }})) >> $GITHUB_ENV
            echo -e $(export DLRS_VERSION=$(git tag --sort creatordate -l "v*-RELEASE*" --merged)) >> $GITHUB_ENV

        - name: Print variables
          run: |
            echo "$DLRS_NAME"
            echo ${DLRS_BRANCH}
            echo $DLRS_VERSION

        - name: Print Env
          run: |
            echo $GITHUB_ENV | grep DLRS