name: Release Branch

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
    variables:
      #uses: dolorestec/devops/.github/workflows/release-branch.yml@v1 
      name: Variables
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Creating variables
          run: git --version

        