name: Release Branch

on:
  push:
    branches:
      - develop

jobs:
    release-branch:
      #uses: dolorestec/devops/.github/workflows/release-branch.yml@v1 
      name: Variables
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Creating variables
          run: |
            echo "Creating variables file"
            touch variables && chmod 777 variables

        - name: Setting variables
          env:
            DLRS_NAME: ${{ github.repository }}
            DLRS_BRANCH: ${{ github.ref_name }}
            DLRS_VERSION: $(git tag --sort creatordate -l "v*-RELEASE*" --merged)       
          run: |
            echo "Setting variables in variables file"
            echo ${{env.DLRS_NAME}} >> variables
            echo ${{env.DLRS_BRANCH}} >> variables
            echo ${{env.DLRS_VERSION}} >> variables


        - name: Upload variables
          uses: actions/upload-artifact@v2
          with:
            name: variables
            path: variables