name: Release Branch

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
    release-branch:
      #uses: dolorestec/devops/.github/workflows/release-branch.yml@v1 
      name: Variables
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Setting variables
          env:
            DLRS_NAME: ${{ github.repository }}
            DLRS_BRANCH: ${{ github.ref_name }}
            DLRS_VERSION: $(git tag --sort creatordate -l "v*-RELEASE*" --merged)
          run: |
            echo ${{env.DLRS_NAME}}
            echo ${{env.DLRS_BRANCH}}
            echo ${{env.DLRS_VERSION}}