name: Release Candidate

on:
  push:
  workflow_dispatch:

env:
  colors:
    RED='\033[0;31m'    
    GREEN='\033[0;32m'    
    YELLOW='\033[1;33m' 
    WHITE='\033[1;37m'
    SET='\033[0m'

jobs:
    envoirenment:
        name: Envoirenment
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                repository: ${{ github.repository }}
                ref: ${{ github.ref_name }}
                fetch-depth: 0
            
            - name: Setting variables
              uses: ./.github/actions/utils/variables
              with:
                colors: ${{ env.colors }}

            - name: Upload variables as artifacts
              run: |
                echo $FBA_IMAGE_NAME           
