name: Release Candidate

on:
  workflow_dispatch:

jobs:
    envoirenment:
          name: Envoirenment
          uses: dolorestec/devops/.github/workflows/envoirenment.yml@v1 
          with:
              image_name: ${{ github.repository }}
              image_tag: ${{ github.ref_name }}
          

