name: Release Branch

on:
  push:
    branches:
      - develop
    tags:
      - v*-RELEASE*

  workflow_dispatch:

jobs:
    variables:
      #uses: dolorestec/devops/.github/workflows/release-branch.yml@v1 
      name: Variables
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Setting variables
          run: |
            echo "Setting variables in variables file"
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo -e DLRS_NAME=${{ github.repository }} >> "$GITHUB_ENV"
            echo -e DLRS_BRANCH=${{ github.ref_name }} >> "$GITHUB_ENV"
            echo -e DLRS_VERSION=$(git tag --sort creatordate -l "v*-RELEASE*" --merged | tail -n 1) >> "$GITHUB_ENV"
            echo "$EOF" >> "$GITHUB_ENV

        - name: Upload variables
          run: |
            echo ${{env.DLRS_NAME}}
  
    docker:
      name: Docker
      runs-on: ubuntu-latest
      needs: variables
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref_name }}
            fetch-depth: 0

        - name: Download variables
          uses: actions/download-artifact@v2
          with:
            name: variables

        - name: Setting variables
          run: |
            echo "Setting variables from variables file"
            source variables.txt
            echo $DLRS_NAME
            echo $DLRS_BRANCH
            echo $DLRS_VERSION

        - name: Docker build
          run: |
            echo "Building docker image" 
            docker build . --tag $DLRS_NAME:$DLRS_VERSION

        - name: Docker login
          run: |
            echo "Logging into docker"
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
        - name: Docker push
          run: |
            echo "Pushing docker image"
            docker push $DLRS_NAME:$DLRS_VERSION

        - name: Docker logout
          run: |
            echo "Logging out of docker"
            docker logout

    release_branch:
      
        name: Release Branch
        runs-on: ubuntu-latest
        needs: docker
        steps:
          - name: Checkout
            run:
              echo "Checking out"
              git checkout $DLRS_BRANCH
    
