name: Release Candidate

on:
  push:
  workflow_dispatch:

jobs:
    envoirenment:
        name: Envoirenment
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                repository: ${{ github.repository }}
                ref: ${{ github.ref_name }}
                fetch-depth: 0
            
            - name: Setting variables
              uses: ./.github/actions/utils/variables

            - name: Upload variables as artifacts
              run: |
                touch variables && chmod 777 variables;
                for var in ${{toJson(env)}}; do
                    echo $var >> variables;
                done
                

