name: Release Candidate

on:
  push:
  workflow_dispatch:

jobs:
    envoirenment:
        name: Envoirenment
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                repository: ${{ github.repository }}
                ref: ${{ github.ref_name }}
                fetch-depth: 0
            
            - name: Setting variables
              uses: ./.github/actions/utils/variables

    build:
      name: Build
      timeout-minutes: 10
      runs-on: ubuntu-latest

      needs: envoirenment

      steps:
        - name: Download Artifact
          uses: actions/download-artifact@v3
          with:
            name: variables

        - name: Setting variables
          run: |
            echo "Setting variables"; \
            cat variables.txt; \