name: Release Branch

on:
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
    validation:
      name: Validation
      uses: dolorestec/devops/.github/workflows/release-branch.yml@v1 
          

